"""Generate the two demo label images shown on the API landing page.

Deterministic (pure PIL drawing, no randomness) so the committed PNGs can be
regenerated byte-similar at any time:
    python scripts/make_demo_labels.py
"""

import os

from PIL import Image, ImageDraw, ImageFont

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "demo")

W, H = 900, 1200


def _font(size: int, bold: bool = False):
    for name in (("arialbd.ttf" if bold else "arial.ttf"), "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _barcode(draw: ImageDraw.ImageDraw, x: int, y: int, w: int, h: int) -> None:
    """A decorative EAN-13-style bar block (deterministic widths)."""
    widths = [3, 1, 2, 1, 3, 1, 1, 2, 1, 3, 2, 1, 1, 2, 3, 1, 1, 1, 2, 1, 3, 1, 2, 2, 1, 3, 1, 1]
    cx = x
    for i, bw in enumerate(widths * 2):
        if i * 2 >= w:
            break
        if i % 2 == 0:
            draw.rectangle([cx, y, cx + bw, y + h], fill=(17, 24, 39))
        cx += bw
        if cx > x + w:
            break


def compliant_label() -> None:
    img = Image.new("RGB", (W, H), (253, 250, 240))
    d = ImageDraw.Draw(img)

    d.rectangle([0, 0, W, 210], fill=(180, 83, 9))
    d.rectangle([0, 210, W, 228], fill=(146, 64, 14))
    d.text((60, 60), "CRISPY COOKIES", font=_font(72, bold=True), fill=(255, 251, 235))
    d.text((62, 150), "Butter Baked Snack  |  100 g Pack", font=_font(30), fill=(255, 237, 213))

    y = 290
    rows = [
        ("Net Quantity: 100 g", 34, (23, 32, 51)),
        ("M.R.P.: Rs. 25.00 (inclusive of all taxes)", 34, (23, 32, 51)),
        ("Mfg Date: 02/2026   Best Before: 08/2026", 30, (55, 65, 81)),
        ("Mfd By: ACME Foods Pvt. Ltd.", 30, (55, 65, 81)),
        ("5/1A Hungerford Street, Kolkata - 700017", 30, (55, 65, 81)),
        ("Consumer Care: 1800-425-4449", 28, (55, 65, 81)),
        ("feedback@acmefoods.co.in", 28, (55, 65, 81)),
        ("FSSAI Lic. No.: 10015043001129", 28, (55, 65, 81)),
        ("Ingredients: Refined Wheat Flour, Sugar,", 26, (75, 85, 99)),
        ("Edible Vegetable Oil, Butter, Milk Solids", 26, (75, 85, 99)),
    ]
    for text, size, color in rows:
        d.text((60, y), text, font=_font(size), fill=color)
        y += size + 26

    # Veg symbol: green dot inside a green square outline (top-right convention)
    d.rectangle([W - 140, 300, W - 60, 380], outline=(21, 128, 61), width=5)
    d.ellipse([W - 122, 318, W - 78, 362], fill=(21, 128, 61))

    _barcode(d, 60, H - 220, 380, 130)
    d.text((470, H - 200), "8 901234 567890", font=_font(30), fill=(17, 24, 39))
    d.text((60, H - 60), "STORE IN A COOL, DRY PLACE", font=_font(22), fill=(107, 114, 128))

    img.save(os.path.join(OUT_DIR, "demo_label_compliant.png"), "PNG", optimize=True)


def violation_label() -> None:
    img = Image.new("RGB", (W, H), (248, 250, 252))
    d = ImageDraw.Draw(img)

    d.rectangle([0, 0, W, 190], fill=(30, 58, 95))
    d.text((60, 55), "SHINE DETERGENT", font=_font(64, bold=True), fill=(224, 242, 254))
    d.text((62, 135), "Now in new look!", font=_font(30), fill=(165, 216, 232))

    y = 270
    rows = [
        ("Net Wt. 500 g", 36, (23, 32, 51)),
        ("A premium wash, every time.", 30, (55, 65, 81)),
        ("Mfd By: Shine Household Products", 28, (55, 65, 81)),
        ("Plot 21, Industrial Area, Phase II", 28, (55, 65, 81)),
        ("FSSAI Lic. No.: 10015043001129", 26, (55, 65, 81)),
    ]
    for text, size, color in rows:
        d.text((60, y), text, font=_font(size), fill=color)
        y += size + 30

    # A detergent pack would not need FSSAI, but this demo label also omits
    # the MRP, the manufacture month/year, the PIN code and consumer care —
    # the declaration gaps the rule engine is meant to catch.
    _barcode(d, 60, H - 200, 340, 120)
    d.text((60, H - 60), "FOR LAUNDRY USE ONLY", font=_font(22), fill=(107, 114, 128))

    img.save(os.path.join(OUT_DIR, "demo_label_violation.png"), "PNG", optimize=True)


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    compliant_label()
    violation_label()
    print(f"[OK] demo images written to {OUT_DIR}")


if __name__ == "__main__":
    main()
